
--
-- This currently does tests for dark mode only
-- Tests related to interface changes , client side
--

-- PROBLEMS:
-- TODO

--------------------------------------------------------------------------------
insulate("cl - Play", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Play different after play", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_play_different(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Play after pause", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_pause_play(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Play after autoplay", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_autoplay_play(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Play same after play", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_restart(dermaBase, media.cl_PlayingSong)
end)
--------------------------------------------------------------------------------

insulate("cl - Pause after play", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_pause(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Pause after pause", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_pause_unpause(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Pause after loop", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_loop_pause(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Pause after autoplay", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_autoplay_pause(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Unpause after loop & pause", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_loop_pause_unpause(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Unpause after autoplay & pause", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_autoplay_pause_unpause(dermaBase, media.cl_PlayingSong)
end)
--------------------------------------------------------------------------------

insulate("cl - Stop after play", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_stop(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Stop after pause", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_pause_stop(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Stop after unpause", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_pause_unpause_stop(dermaBase, media.cl_PlayingSong)
end)
--------------------------------------------------------------------------------

insulate("cl - Loop after play", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_loop(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Loop after pause", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_pause_loop(dermaBase, media.cl_PlayingSong)
end)
--------------------------------------------------------------------------------

insulate("cl - Autoplay after play", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_autoplay(dermaBase, media.cl_PlayingSong)
end)
insulate("cl - Autoplay while seek end", function()
  local dermaBase, media = create_with_dark_mode()
  assert.set_derma(dermaBase)
  sh_play_autoplay_seekend(dermaBase, media.cl_PlayingSong)
end)
--------------------------------------------------------------------------------
