-- util.AddNetworkString("sendServerSettings")
util.AddNetworkString("cl_update_cvars_from_first_admin")
util.AddNetworkString("sv_update_cvars_from_first_admin")
util.AddNetworkString("cl_update_cvars")
util.AddNetworkString("cl_gmpl_create")
util.AddNetworkString("sv_keypress_F3")
util.AddNetworkString("sv_gmpl_show")
util.AddNetworkString("cl_gmpl_show")
util.AddNetworkString("sv_set_seek")
util.AddNetworkString("cl_set_seek")
-------------------------------------------------------------------------------
util.AddNetworkString("sv_play_live")
util.AddNetworkString("cl_play_live")
util.AddNetworkString("sv_stop_live")
util.AddNetworkString("cl_stop_live")
util.AddNetworkString("sv_set_loop")
util.AddNetworkString("cl_set_loop")
util.AddNetworkString("sv_set_autoplay")
util.AddNetworkString("cl_set_autoplay")
util.AddNetworkString("sv_pause_live")
util.AddNetworkString("cl_pause_live")
util.AddNetworkString("sv_update_channel_data")
-------------------------------------------------------------------------------
-- Live Seek Logic
-------------------------------------------------------------------------------
-- util.AddNetworkString("askAdminForLiveSeek")
-- util.AddNetworkString("toServerUpdateSeek")
-- util.AddNetworkString("playLiveSeek")
-------------------------------------------------------------------------------
-- Sanity Checks for live seek and other
-------------------------------------------------------------------------------
-- util.AddNetworkString("updateStatusPauseToServer")
util.AddNetworkString("sv_play_live_seek_from_host")
util.AddNetworkString("cl_play_live_seek_from_host")
util.AddNetworkString("sv_play_live_seek_for_user")
util.AddNetworkString("cl_play_live_seek")
util.AddNetworkString("cl_play_live_seek__admin_only")
util.AddNetworkString("sv_play_live_seek")
util.AddNetworkString("cl_play_next")
util.AddNetworkString("sv_refresh_song_state")
util.AddNetworkString("cl_refresh_song_state")
util.AddNetworkString("sv_update_song_state")
-- util.AddNetworkString("sv_update_host")
-- util.AddNetworkString("cl_update_host")
-------------------------------------------------------------------------------
-- util.AddNetworkString("toServerRefreshAccessDir")
-- util.AddNetworkString("refreshAdminAccessDir")
util.AddNetworkString("sv_refresh_song_list")
util.AddNetworkString("cl_refresh_song_list")
util.AddNetworkString("sv_reset_audio")
-------------------------------------------------------------------------------
util.AddNetworkString("sv_ask_server_settings")
util.AddNetworkString("cl_ask_server_settings")
util.AddNetworkString("sv_ask_live_channel_data")
util.AddNetworkString("cl_ask_live_channel_data")
-------------------------------------------------------------------------------
util.AddNetworkString("cl_settings_update")
util.AddNetworkString("sv_settings_edit_live_access")
-- util.AddNetworkString("cl_settings_edit_live_access")
util.AddNetworkString("sv_settings_edit_dir_access")
-- util.AddNetworkString("cl_settings_edit_dir_access")